name: clang-format

on:
  pull_request:
    types:
      - opened

jobs:
  auto-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "src"
          extensions: "cpp,hpp"
          clangFormatVersion: 12
          inplace: True

      - name: Verify changed files
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v8.8

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Run clang-format
