name: cmake

on:
  workflow_run:
    workflows: [clang-format]
    types:
      - completed
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi"
          buildPreset: "ninja-multi-debug"
          testPreset: "ninja-multi-debug"
