name: CMake

on:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Initialize submodules
      run: >
        git submodule init &&
        git submodule update

    - name: Configure CMake
      run: >
        cmake
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build project
      run: >
        cmake 
        --build ${{github.workspace}}/build 
        --config ${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: >
        ctest 
        -C ${{env.BUILD_TYPE}}
