name: CMake

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [windows-2022, ubuntu-20.04, macos-11]
        os: [ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi"
          buildPreset: "ninja-multi-debug"
          testPreset: "ninja-multi-debug"

      - name: Run clang-format
        run: make clang-format
