name: CMake

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-11, windows-2022]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi"
          buildPreset: "ninja-multi-debug"
          testPreset: "ninja-multi-debug"
