name: CMake

#TODO: Fix linking issues.
#on:
#  pull_request:
#    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialize submodules
      run: >
        git submodule init &&
        git submodule update

    - name: Bootstrap vcpkg
      run: ./external/vcpkg/bootstrap-vcpkg.sh -disableMetrics

    - name: Install dependencies
      run: ./external/vcpkg/vcpkg install

    - name: Configure build
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DC_CXX_COMPILER=clang

    - name: Build code
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
