name: GitHub Actions

on:
  pull_request:
    branches:    
      - main
  schedule:
    - cron: "0 0 * * SUN"

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}  
          submodules: true

      - name: Format code
        if: matrix.os == 'ubuntu-latest'
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "src"
          extensions: "cc,h"
          clangFormatVersion: 12
          inplace: True

      - name: Verify changed files
        if: matrix.os == 'ubuntu-latest'
        uses: tj-actions/verify-changed-files@v8.8
        id: verify-changed-files

      - name: Commit changes
        if: matrix.os == 'ubuntu-latest' && steps.verify-changed-files.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Format code

      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"

      - name: Replace CMakeSettings.json with CMakePresets.json
        shell: bash
        run: |
          rm CMakeSettings.json
          mv tools/CMakePresets.json .

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg-debug'
          testPreset: 'ninja-multi-vcpkg-debug'
