name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
          submodules: true

      # Auto-format on Ubuntu
      # The Ubuntu build runs the fastest so we can slide this in for free

      - name: Format code
        if: matrix.os == 'ubuntu-latest'
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "src"
          extensions: "cpp,hpp"
          clangFormatVersion: 12
          inplace: True

      - name: Verify changed files
        id: verify-changed-files
        if: matrix.os == 'ubuntu-latest'
        uses: tj-actions/verify-changed-files@v8.8

      - name: Commit changes
        if: matrix.os == 'ubuntu-latest' && steps.verify-changed-files.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Format code

      # Build on all available OS

      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2

      - name: Install project dependencies
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"

      - name: Build and test
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi"
          buildPreset: "ninja-multi-debug"
          testPreset: "ninja-multi-debug"

      # Auto-lint on Ubuntu
      # Probably waiting for Windows and macOS build to finish anyways

      - name: Install clang-tidy
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y clang-tidy

      - name: Analyze code
        if: matrix.os == 'ubuntu-latest'
        run: git diff -U0 HEAD^ | clang-tidy-diff -p1 -path build -export-fixes build/clang-tidy-fixes.yml

      - name: Request changes
        if: matrix.os == 'ubuntu-latest'
        uses: platisd/clang-tidy-pr-comments@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: build/clang-tidy-fixes.yml
          request_changes: true
